
function Test_recv()
    -- local msg = message(protocol.send_1) 
    -- msg.seg1 = 4
    -- msg.seg2 = {0,2,3, 4}
    send(device.dev2.u2, "msf\0",{to="dev12.s1"})
    delay(1000)
    local s1, s2 = recv(device.dev2.uu2, nil);
    print(s1,s2)
end

function Demo_log()

    log.step("测试项1")
    delay(300)
    log.action("执行xxx1操作")
    delay(300)
    log.warn("报警信息aaa")
    delay(300)
    log.action("执行xxx3操作")
    delay(300)
    log.step("测试项2")
    delay(300)
    log.action("执行yyy1操作:打开开关xx，然后关闭开关yy")
    delay(300)
    -- log.error("错误信息yyy")
    delay(300)
    log.action("执行yyy3操作")
    delay(300)
    log.step("测试项3")
    delay(300)
    log.action("执行zzz1操作")
    delay(300)
    verify(false, "验证aaa失败")
    print('printa', 'pringb')
    delay(300)
    log.info("普通信息efg")
    delay(300)
    log.action("执行zzz3操作")
    print('printc')
    delay(300)
    log.step("测试项4")
    delay(300)
    log.check("检查abc1的开个处于打开状态", true)
    delay(300)
    log.check("检查abc2的电压值大于20v", true)
    delay(300)
    log.check("检查abc3的电流小于100ma", false)
    delay(300)
    assert(false, '用例执行失败')
end

function entry()
    Demo_log()
    exit()
end